version: 1.0
provider:
  name: openfaas
  gateway: http://gateway.openfaas:8080
  network: openfaas-fn

functions:
  generate-password:
    lang: python3
    handler: ./functions/generate-password
    image: cofrap/generate-password:latest
    environment:
      DATABASE_URL: "postgresql://cofrap:cofrap@postgres:5432/cofrap"
    secrets:
      - encryption-key
    environment_file:
      - .env.secrets

  generate-2fa:
    lang: python3
    handler: ./functions/generate-2fa
    image: cofrap/generate-2fa:latest
    environment:
      DATABASE_URL: "postgresql://cofrap:cofrap@postgres:5432/cofrap"
    secrets:
      - encryption-key
    environment_file:
      - .env.secrets

  authenticate:
    lang: python3
    handler: ./functions/authenticate
    image: cofrap/authenticate:latest
    environment:
      DATABASE_URL: "postgresql://cofrap:cofrap@postgres:5432/cofrap"
    secrets:
      - encryption-key
    environment_file:
      - .env.secrets

  recover-with-backup-code:
    lang: python3
    handler: ./functions/recover-with-backup-code
    image: cofrap/recover-with-backup-code:latest
    environment:
      DATABASE_URL: "postgresql://cofrap:cofrap@postgres:5432/cofrap"
    secrets:
      - encryption-key
    environment_file:
      - .env.secrets
