apiVersion: v1
kind: Secret
metadata:
  name: cofrap-secrets
  namespace: cofrap
type: Opaque
stringData:
  encryption-key: "GqJ4Y6dM9vQ8XzN3Hk7Pa2sBcRfTwUyL5jE0iVoWnZE="  # ⚠️ CHANGEZ CETTE CLE - voir docs/deploy.md
  database-url: "postgresql://cofrap:cofrap@postgres.cofrap.svc.cluster.local:5432/cofrap"
  postgres-password: "cofrap"
  postgres-user: "cofrap"
  postgres-db: "cofrap"
